/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.kartodromo.view;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Arthur
 */
public class DialogOption extends javax.swing.JDialog {

    private Color defaultColor = new Color(35, 40, 44);
    private Color defaultClickedColor = new Color(60, 63, 65);

    public DialogOption( String message) {
        this.setUndecorated(true);

        initComponents();
        instantiateElements(message);
    }

    private void instantiateElements(String message) {
        lbIcon.setBackground(defaultColor);
        lbIcon.setIcon(new ImageIcon(getClass().getResource("/images/menuIcons/icon_error_light.png")));
        lbTitle.setText(message);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBody = new javax.swing.JPanel();
        jpContent = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();
        btnNao = new javax.swing.JPanel();
        btnN = new javax.swing.JLabel();
        btnSim = new javax.swing.JPanel();
        btnBotao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 150));

        jpBody.setBackground(new java.awt.Color(35, 40, 44));
        jpBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jpBody.setPreferredSize(new java.awt.Dimension(300, 150));

        jpContent.setBackground(new java.awt.Color(35, 40, 44));

        lbTitle.setBackground(new java.awt.Color(204, 204, 204));
        lbTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(204, 204, 204));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitle.setText("Título Lorem Ipsum");
        lbTitle.setPreferredSize(new java.awt.Dimension(175, 50));

        lbIcon.setBackground(new java.awt.Color(204, 204, 204));
        lbIcon.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbIcon.setForeground(new java.awt.Color(204, 204, 204));
        lbIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNao.setBackground(new java.awt.Color(35, 40, 44));
        btnNao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnNao.setPreferredSize(new java.awt.Dimension(100, 35));
        btnNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNaoMouseReleased(evt);
            }
        });

        btnN.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnN.setForeground(new java.awt.Color(204, 204, 204));
        btnN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnN.setText("Não");
        btnN.setPreferredSize(new java.awt.Dimension(86, 21));

        javax.swing.GroupLayout btnNaoLayout = new javax.swing.GroupLayout(btnNao);
        btnNao.setLayout(btnNaoLayout);
        btnNaoLayout.setHorizontalGroup(
            btnNaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnN, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnNaoLayout.setVerticalGroup(
            btnNaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnN, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        btnSim.setBackground(new java.awt.Color(35, 40, 44));
        btnSim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnSim.setPreferredSize(new java.awt.Dimension(100, 35));
        btnSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSimMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSimMouseReleased(evt);
            }
        });

        btnBotao.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnBotao.setForeground(new java.awt.Color(204, 204, 204));
        btnBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBotao.setText("Sim");
        btnBotao.setPreferredSize(new java.awt.Dimension(86, 21));
        btnBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBotaoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnSimLayout = new javax.swing.GroupLayout(btnSim);
        btnSim.setLayout(btnSimLayout);
        btnSimLayout.setHorizontalGroup(
            btnSimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        btnSimLayout.setVerticalGroup(
            btnSimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnNao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jpContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBody, javax.swing.GroupLayout.Alignment.TRAILING, 310, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBody, 159, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNaoMousePressed
        btnNao.setBackground(defaultClickedColor);
    }//GEN-LAST:event_btnNaoMousePressed

    private void btnNaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNaoMouseReleased
        btnNao.setBackground(defaultColor);
        this.setVisible(false);
    }//GEN-LAST:event_btnNaoMouseReleased

    private void btnSimMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimMousePressed

    private void btnSimMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimMouseReleased
        btnNao.setBackground(defaultColor);
        this.setVisible(true);
    }//GEN-LAST:event_btnSimMouseReleased

    private void btnBotaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBotaoMouseReleased
        
        
        
    }//GEN-LAST:event_btnBotaoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogOption dialog = new DialogOption("teste");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JPanel getBtnNao() {
        return btnNao;
    }

    public void setBtnNao(JPanel btnNao) {
        this.btnNao = btnNao;
    }

    public JPanel getBtnSim() {
        return btnSim;
    }

    public void setBtnSim(JPanel btnSim) {
        this.btnSim = btnSim;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBotao;
    private javax.swing.JLabel btnN;
    private javax.swing.JPanel btnNao;
    private javax.swing.JPanel btnSim;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpContent;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
