/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.kartodromo.view;

import java.awt.Color;

/**
 *
 * @author Arthur
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        tabAgendamentos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabPlacar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tabPaddock = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tabIniciarCorrida = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tabCadastros = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tabFinanceiro = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tabSobre = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpContent = new javax.swing.JPanel();
        jpAgendamentos = new javax.swing.JPanel();
        jpIniciarCorrida = new javax.swing.JPanel();
        jpPlacar = new javax.swing.JPanel();
        jpPaddock = new javax.swing.JPanel();
        jpCadastros = new javax.swing.JPanel();
        jpFinanceiro = new javax.swing.JPanel();
        jpSobre = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpMenu.setBackground(new java.awt.Color(0, 28, 57));

        tabAgendamentos.setBackground(new java.awt.Color(219, 10, 64));
        tabAgendamentos.setPreferredSize(new java.awt.Dimension(250, 30));
        tabAgendamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabAgendamentosMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agendamentos");
        jLabel1.setPreferredSize(new java.awt.Dimension(94, 18));

        javax.swing.GroupLayout tabAgendamentosLayout = new javax.swing.GroupLayout(tabAgendamentos);
        tabAgendamentos.setLayout(tabAgendamentosLayout);
        tabAgendamentosLayout.setHorizontalGroup(
            tabAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAgendamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabAgendamentosLayout.setVerticalGroup(
            tabAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAgendamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPlacar.setBackground(new java.awt.Color(219, 10, 64));
        tabPlacar.setPreferredSize(new java.awt.Dimension(250, 30));
        tabPlacar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPlacarMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Placar");
        jLabel2.setPreferredSize(new java.awt.Dimension(37, 18));

        javax.swing.GroupLayout tabPlacarLayout = new javax.swing.GroupLayout(tabPlacar);
        tabPlacar.setLayout(tabPlacarLayout);
        tabPlacarLayout.setHorizontalGroup(
            tabPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPlacarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabPlacarLayout.setVerticalGroup(
            tabPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPlacarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPaddock.setBackground(new java.awt.Color(219, 10, 64));
        tabPaddock.setPreferredSize(new java.awt.Dimension(250, 30));
        tabPaddock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPaddockMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Paddock");
        jLabel3.setPreferredSize(new java.awt.Dimension(53, 18));

        javax.swing.GroupLayout tabPaddockLayout = new javax.swing.GroupLayout(tabPaddock);
        tabPaddock.setLayout(tabPaddockLayout);
        tabPaddockLayout.setHorizontalGroup(
            tabPaddockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaddockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabPaddockLayout.setVerticalGroup(
            tabPaddockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaddockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabIniciarCorrida.setBackground(new java.awt.Color(219, 10, 64));
        tabIniciarCorrida.setPreferredSize(new java.awt.Dimension(250, 30));
        tabIniciarCorrida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabIniciarCorridaMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Iniciar Corrida");
        jLabel4.setPreferredSize(new java.awt.Dimension(88, 18));

        javax.swing.GroupLayout tabIniciarCorridaLayout = new javax.swing.GroupLayout(tabIniciarCorrida);
        tabIniciarCorrida.setLayout(tabIniciarCorridaLayout);
        tabIniciarCorridaLayout.setHorizontalGroup(
            tabIniciarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabIniciarCorridaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabIniciarCorridaLayout.setVerticalGroup(
            tabIniciarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabIniciarCorridaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabCadastros.setBackground(new java.awt.Color(219, 10, 64));
        tabCadastros.setPreferredSize(new java.awt.Dimension(250, 30));
        tabCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCadastrosMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cadastros");
        jLabel5.setPreferredSize(new java.awt.Dimension(61, 18));

        javax.swing.GroupLayout tabCadastrosLayout = new javax.swing.GroupLayout(tabCadastros);
        tabCadastros.setLayout(tabCadastrosLayout);
        tabCadastrosLayout.setHorizontalGroup(
            tabCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabCadastrosLayout.setVerticalGroup(
            tabCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabFinanceiro.setBackground(new java.awt.Color(219, 10, 64));
        tabFinanceiro.setPreferredSize(new java.awt.Dimension(250, 30));
        tabFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabFinanceiroMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Financeiro");
        jLabel6.setPreferredSize(new java.awt.Dimension(66, 18));

        javax.swing.GroupLayout tabFinanceiroLayout = new javax.swing.GroupLayout(tabFinanceiro);
        tabFinanceiro.setLayout(tabFinanceiroLayout);
        tabFinanceiroLayout.setHorizontalGroup(
            tabFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFinanceiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabFinanceiroLayout.setVerticalGroup(
            tabFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFinanceiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabSobre.setBackground(new java.awt.Color(219, 10, 64));
        tabSobre.setPreferredSize(new java.awt.Dimension(250, 30));
        tabSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabSobreMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sobre");
        jLabel7.setPreferredSize(new java.awt.Dimension(66, 18));

        javax.swing.GroupLayout tabSobreLayout = new javax.swing.GroupLayout(tabSobre);
        tabSobre.setLayout(tabSobreLayout);
        tabSobreLayout.setHorizontalGroup(
            tabSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabSobreLayout.setVerticalGroup(
            tabSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabIniciarCorrida, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(tabAgendamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(tabPlacar, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(tabPaddock, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(tabCadastros, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(tabFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(tabSobre, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel8)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addComponent(tabIniciarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPlacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPaddock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpContent.setPreferredSize(new java.awt.Dimension(575, 500));

        jpAgendamentos.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpAgendamentosLayout = new javax.swing.GroupLayout(jpAgendamentos);
        jpAgendamentos.setLayout(jpAgendamentosLayout);
        jpAgendamentosLayout.setHorizontalGroup(
            jpAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        jpAgendamentosLayout.setVerticalGroup(
            jpAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jpIniciarCorrida.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpIniciarCorridaLayout = new javax.swing.GroupLayout(jpIniciarCorrida);
        jpIniciarCorrida.setLayout(jpIniciarCorridaLayout);
        jpIniciarCorridaLayout.setHorizontalGroup(
            jpIniciarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        jpIniciarCorridaLayout.setVerticalGroup(
            jpIniciarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jpPlacar.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpPlacarLayout = new javax.swing.GroupLayout(jpPlacar);
        jpPlacar.setLayout(jpPlacarLayout);
        jpPlacarLayout.setHorizontalGroup(
            jpPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        jpPlacarLayout.setVerticalGroup(
            jpPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jpPaddock.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpPaddockLayout = new javax.swing.GroupLayout(jpPaddock);
        jpPaddock.setLayout(jpPaddockLayout);
        jpPaddockLayout.setHorizontalGroup(
            jpPaddockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );
        jpPaddockLayout.setVerticalGroup(
            jpPaddockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jpCadastros.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpCadastrosLayout = new javax.swing.GroupLayout(jpCadastros);
        jpCadastros.setLayout(jpCadastrosLayout);
        jpCadastrosLayout.setHorizontalGroup(
            jpCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );
        jpCadastrosLayout.setVerticalGroup(
            jpCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jpFinanceiro.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpFinanceiroLayout = new javax.swing.GroupLayout(jpFinanceiro);
        jpFinanceiro.setLayout(jpFinanceiroLayout);
        jpFinanceiroLayout.setHorizontalGroup(
            jpFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );
        jpFinanceiroLayout.setVerticalGroup(
            jpFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jpSobre.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpSobreLayout = new javax.swing.GroupLayout(jpSobre);
        jpSobre.setLayout(jpSobreLayout);
        jpSobreLayout.setHorizontalGroup(
            jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        jpSobreLayout.setVerticalGroup(
            jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPaddock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpAgendamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpPlacar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpIniciarCorrida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpCadastros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPaddock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpAgendamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpPlacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpIniciarCorrida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpCadastros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSobreMouseClicked
        hideAllPannels();
        jpSobre.setVisible(true);
        tabSobre.setBackground(new Color(255, 211, 1));
    }//GEN-LAST:event_tabSobreMouseClicked

    private void tabFinanceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFinanceiroMouseClicked
        hideAllPannels();
        jpFinanceiro.setVisible(true);
        tabFinanceiro.setBackground(new Color(255, 211, 1));
    }//GEN-LAST:event_tabFinanceiroMouseClicked

    private void tabCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCadastrosMouseClicked
        hideAllPannels();
        jpCadastros.setVisible(true);
        tabCadastros.setBackground(new Color(255, 211, 1));
    }//GEN-LAST:event_tabCadastrosMouseClicked

    private void tabIniciarCorridaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabIniciarCorridaMouseClicked
        hideAllPannels();
        jpIniciarCorrida.setVisible(true);
        tabIniciarCorrida.setBackground(new Color(255, 211, 1));
    }//GEN-LAST:event_tabIniciarCorridaMouseClicked

    private void tabPaddockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPaddockMouseClicked
        hideAllPannels();
        jpPaddock.setVisible(true);
        tabPaddock.setBackground(new Color(255, 211, 1));
    }//GEN-LAST:event_tabPaddockMouseClicked

    private void tabPlacarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPlacarMouseClicked
        hideAllPannels();
        jpPlacar.setVisible(true);
        tabPlacar.setBackground(new Color(255, 211, 1));
    }//GEN-LAST:event_tabPlacarMouseClicked

    private void tabAgendamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabAgendamentosMouseClicked
        hideAllPannels();
        jpAgendamentos.setVisible(true);
        tabAgendamentos.setBackground(new Color(255, 211, 1));
    }//GEN-LAST:event_tabAgendamentosMouseClicked

    private void hideAllPannels() {
        jpIniciarCorrida.setVisible(false);
        jpAgendamentos.setVisible(false);
        jpCadastros.setVisible(false);
        jpFinanceiro.setVisible(false);
        jpPaddock.setVisible(false);
        jpPlacar.setVisible(false);
        jpSobre.setVisible(false);
        
        tabAgendamentos.setBackground(new Color(219,10,64));
        tabCadastros.setBackground(new Color(219,10,64));
        tabFinanceiro.setBackground(new Color(219,10,64));
        tabIniciarCorrida.setBackground(new Color(219,10,64));
        tabPaddock.setBackground(new Color(219,10,64));
        tabPlacar.setBackground(new Color(219,10,64));
        tabSobre.setBackground(new Color(219,10,64));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jpAgendamentos;
    private javax.swing.JPanel jpCadastros;
    private javax.swing.JPanel jpContent;
    private javax.swing.JPanel jpFinanceiro;
    private javax.swing.JPanel jpIniciarCorrida;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpPaddock;
    private javax.swing.JPanel jpPlacar;
    private javax.swing.JPanel jpSobre;
    private javax.swing.JPanel tabAgendamentos;
    private javax.swing.JPanel tabCadastros;
    private javax.swing.JPanel tabFinanceiro;
    private javax.swing.JPanel tabIniciarCorrida;
    private javax.swing.JPanel tabPaddock;
    private javax.swing.JPanel tabPlacar;
    private javax.swing.JPanel tabSobre;
    // End of variables declaration//GEN-END:variables
}
