/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.kartodromo.view.form.home.calendario;

import java.awt.Component;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Arthur
 */
public class PanelDate extends javax.swing.JLayeredPane {

    private int month;
    private int year;

    public PanelDate(int month, int year) {
        initComponents();

        this.month = month;
        this.year = year;

        init();
    }

    private void init() {
        dom.asTitle();
        seg.asTitle();
        ter.asTitle();
        qua.asTitle();
        qui.asTitle();
        sex.asTitle();
        sab.asTitle();

        setDate();
    }

    private void setDate() {
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, month);
        calendar.set(Calendar.DATE, 1);
        int startDay = calendar.get(Calendar.DAY_OF_WEEK) - 1;
        calendar.add(Calendar.DATE, -startDay);

        Today today = getToday();

        for (Component com : getComponents()) {
            CellCalendarVO cell = (CellCalendarVO) com;
            if (!cell.isTitle()) {
                cell.setText(calendar.get(Calendar.DATE) + "");
                cell.setDate(calendar.getTime());
                cell.currentMonth(calendar.get(Calendar.MONTH) == month);
                if (today.isToday(new Today(calendar.get(Calendar.DATE), calendar.get(Calendar.MONTH), calendar.get(Calendar.YEAR)))) {
                    cell.setAsToday();
                }
                calendar.add(Calendar.DATE, 1);
            }
        }
    }

    private Today getToday() {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        return new Today(calendar.get(Calendar.DATE), calendar.get(Calendar.MONTH), calendar.get(Calendar.YEAR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dom = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        seg = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        ter = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        qua = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        qui = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        sex = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        sab = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell8 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell9 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell10 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell11 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell12 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell13 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell14 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell15 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell16 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell17 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell18 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell19 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell20 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell21 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell22 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell23 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell24 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell25 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell26 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell27 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell28 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell29 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell30 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell31 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell32 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell33 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell34 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell35 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell36 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell37 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell38 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell39 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell40 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell41 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell42 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell43 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell44 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell45 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell46 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell47 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell48 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();
        cell49 = new br.univates.kartodromo.view.form.home.calendario.CellCalendarVO();

        setBackground(new java.awt.Color(21, 25, 28));
        setLayout(new java.awt.GridLayout(7, 7));

        dom.setForeground(new java.awt.Color(255, 211, 0));
        dom.setText("Dom");
        dom.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(dom);

        seg.setForeground(new java.awt.Color(204, 204, 204));
        seg.setText("Seg");
        seg.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(seg);

        ter.setForeground(new java.awt.Color(204, 204, 204));
        ter.setText("Ter");
        ter.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(ter);

        qua.setForeground(new java.awt.Color(204, 204, 204));
        qua.setText("Qua");
        qua.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(qua);

        qui.setForeground(new java.awt.Color(204, 204, 204));
        qui.setText("Qui");
        qui.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(qui);

        sex.setForeground(new java.awt.Color(204, 204, 204));
        sex.setText("Sex");
        sex.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(sex);

        sab.setForeground(new java.awt.Color(255, 211, 0));
        sab.setText("Sab");
        sab.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(sab);

        cell8.setForeground(new java.awt.Color(204, 204, 204));
        cell8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell8);

        cell9.setForeground(new java.awt.Color(204, 204, 204));
        cell9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell9);

        cell10.setForeground(new java.awt.Color(204, 204, 204));
        cell10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell10);

        cell11.setForeground(new java.awt.Color(204, 204, 204));
        cell11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell11);

        cell12.setForeground(new java.awt.Color(204, 204, 204));
        cell12.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell12);

        cell13.setForeground(new java.awt.Color(204, 204, 204));
        cell13.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell13);

        cell14.setForeground(new java.awt.Color(204, 204, 204));
        cell14.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell14);

        cell15.setForeground(new java.awt.Color(204, 204, 204));
        cell15.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell15);

        cell16.setForeground(new java.awt.Color(204, 204, 204));
        cell16.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell16);

        cell17.setForeground(new java.awt.Color(204, 204, 204));
        cell17.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell17);

        cell18.setForeground(new java.awt.Color(204, 204, 204));
        cell18.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell18);

        cell19.setForeground(new java.awt.Color(204, 204, 204));
        cell19.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell19);

        cell20.setForeground(new java.awt.Color(204, 204, 204));
        cell20.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell20);

        cell21.setForeground(new java.awt.Color(204, 204, 204));
        cell21.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell21);

        cell22.setForeground(new java.awt.Color(204, 204, 204));
        cell22.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell22);

        cell23.setForeground(new java.awt.Color(204, 204, 204));
        cell23.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell23);

        cell24.setForeground(new java.awt.Color(204, 204, 204));
        cell24.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell24);

        cell25.setForeground(new java.awt.Color(204, 204, 204));
        cell25.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell25);

        cell26.setForeground(new java.awt.Color(204, 204, 204));
        cell26.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell26);

        cell27.setForeground(new java.awt.Color(204, 204, 204));
        cell27.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell27);

        cell28.setForeground(new java.awt.Color(204, 204, 204));
        cell28.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell28);

        cell29.setForeground(new java.awt.Color(204, 204, 204));
        cell29.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell29);

        cell30.setForeground(new java.awt.Color(204, 204, 204));
        cell30.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell30);

        cell31.setForeground(new java.awt.Color(204, 204, 204));
        cell31.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell31);

        cell32.setForeground(new java.awt.Color(204, 204, 204));
        cell32.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell32);

        cell33.setForeground(new java.awt.Color(204, 204, 204));
        cell33.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell33);

        cell34.setForeground(new java.awt.Color(204, 204, 204));
        cell34.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell34);

        cell35.setForeground(new java.awt.Color(204, 204, 204));
        cell35.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell35);

        cell36.setForeground(new java.awt.Color(204, 204, 204));
        cell36.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell36);

        cell37.setForeground(new java.awt.Color(204, 204, 204));
        cell37.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell37);

        cell38.setForeground(new java.awt.Color(204, 204, 204));
        cell38.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell38);

        cell39.setForeground(new java.awt.Color(204, 204, 204));
        cell39.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell39);

        cell40.setForeground(new java.awt.Color(204, 204, 204));
        cell40.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell40);

        cell41.setForeground(new java.awt.Color(204, 204, 204));
        cell41.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell41);

        cell42.setForeground(new java.awt.Color(204, 204, 204));
        cell42.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell42);

        cell43.setForeground(new java.awt.Color(204, 204, 204));
        cell43.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell43);

        cell44.setForeground(new java.awt.Color(204, 204, 204));
        cell44.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell44);

        cell45.setForeground(new java.awt.Color(204, 204, 204));
        cell45.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell45);

        cell46.setForeground(new java.awt.Color(204, 204, 204));
        cell46.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell46);

        cell47.setForeground(new java.awt.Color(204, 204, 204));
        cell47.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell47);

        cell48.setForeground(new java.awt.Color(204, 204, 204));
        cell48.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell48);

        cell49.setForeground(new java.awt.Color(204, 204, 204));
        cell49.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        add(cell49);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell10;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell11;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell12;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell13;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell14;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell15;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell16;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell17;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell18;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell19;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell20;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell21;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell22;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell23;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell24;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell25;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell26;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell27;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell28;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell29;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell30;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell31;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell32;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell33;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell34;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell35;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell36;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell37;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell38;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell39;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell40;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell41;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell42;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell43;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell44;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell45;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell46;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell47;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell48;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell49;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell8;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO cell9;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO dom;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO qua;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO qui;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO sab;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO seg;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO sex;
    private br.univates.kartodromo.view.form.home.calendario.CellCalendarVO ter;
    // End of variables declaration//GEN-END:variables
}
