/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.kartodromo.view.form;

import br.univates.kartodromo.controller.AuditoriaController;
import br.univates.kartodromo.model.entity.Auditoria;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arthur
 */
public class FormAuditoria extends javax.swing.JPanel {

    public FormAuditoria() {
        initComponents();

        buildTableAuditoria();
    }

    private void buildTableAuditoria() {
        fillTableAuditoria();
        
        jtAuditoria.getTableHeader().setFont(new Font("Trebuchet MS", Font.BOLD, 12));
        jtAuditoria.getTableHeader().setOpaque(false);
//        jtAuditoria.getTableHeader().setBackground(new Color(69, 73, 74));
        jtAuditoria.getTableHeader().setForeground(new Color(51, 51, 51));
        jtAuditoria.setRowHeight(20);
        
        jtAuditoria.getColumnModel().getColumn(0).setMaxWidth(30);
        jtAuditoria.getColumnModel().getColumn(1).setMaxWidth(100);
        jtAuditoria.getColumnModel().getColumn(2).setMaxWidth(100);
        jtAuditoria.getColumnModel().getColumn(3).setMaxWidth(100);
        jtAuditoria.getColumnModel().getColumn(4).setMaxWidth(200);
        jtAuditoria.getColumnModel().getColumn(5).setMaxWidth(100);
        jtAuditoria.getColumnModel().getColumn(6).setMaxWidth(100);
        jtAuditoria.getColumnModel().getColumn(7).setMaxWidth(100);                
    }

    private void fillTableAuditoria() {
        AuditoriaController auditoriaController = new AuditoriaController();
        List<Auditoria> audit = auditoriaController.getAll();

        DefaultTableModel tableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }            
        };        
        
        tableModel.addColumn("Id");
        tableModel.addColumn("Schema");
        tableModel.addColumn("Tabela");
        tableModel.addColumn("Usuário");
        tableModel.addColumn("Horário");
        tableModel.addColumn("Ação");
        tableModel.addColumn("Dados originais");
        tableModel.addColumn("Dados atuais");
        tableModel.addColumn("Query");
        
        audit.stream().forEach(p -> {
            tableModel.addRow(
                    new Object[]{
                        p.getSequenceId(),
                        p.getSchemaName(),
                        p.getTableName(),
                        p.getUserName(),
                        p.getActionTimeStamp().getTime(),
                        p.getAction(),
                        p.getOriginalData(),
                        p.getNewData(),
                        p.getQuery()
                    }
            );
        });

        this.jtAuditoria.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtAuditoria = new javax.swing.JTable();

        setBackground(new java.awt.Color(224, 224, 224));
        setPreferredSize(new java.awt.Dimension(575, 400));

        jPanel12.setBackground(new java.awt.Color(219, 10, 64));

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Auditoria e Acessos");
        jLabel22.setMaximumSize(new java.awt.Dimension(500, 100));
        jLabel22.setPreferredSize(new java.awt.Dimension(300, 63));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtAuditoria.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtAuditoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 233, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtAuditoria;
    // End of variables declaration//GEN-END:variables
}
