/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.kartodromo.view.form;

import br.univates.kartodromo.controller.AuditoriaController;
import br.univates.kartodromo.model.entity.Auditoria;
import br.univates.kartodromo.model.type.CrudType;
import java.awt.Color;
import java.awt.Font;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arthur
 */
public class FormAuditoria extends javax.swing.JPanel {

    private List<Auditoria> audit;

    public FormAuditoria() {
        initComponents();

        audit = new AuditoriaController().getAll();
        buildTableAuditoria();

        buildFilters();
    }

    private void buildFilters() {
        cbAcao.setModel(new DefaultComboBoxModel<>(CrudType.values()));
        ((DefaultComboBoxModel) cbAcao.getModel()).insertElementAt(null, 0);
        cbAcao.setSelectedIndex(0);
    }

    // CUSTOMIZAR 
    private void buildTableAuditoria() {
        fillTableAuditoria();

        jtAuditoria.getTableHeader().setFont(new Font("Trebuchet MS", Font.BOLD, 12));
        jtAuditoria.getTableHeader().setOpaque(false);
//        jtAuditoria.getTableHeader().setBackground(new Color(69, 73, 74));
        jtAuditoria.getTableHeader().setForeground(new Color(51, 51, 51));
        jtAuditoria.setRowHeight(20);

        setColumnCustomWidth(jtAuditoria, 0, 30);
        setColumnCustomWidth(jtAuditoria, 1, 75);
        setColumnCustomWidth(jtAuditoria, 2, 75);
        setColumnCustomWidth(jtAuditoria, 3, 75);
        setColumnCustomWidth(jtAuditoria, 4, 200);
        setColumnCustomWidth(jtAuditoria, 5, 40);
        setColumnCustomWidth(jtAuditoria, 6, 100);
        setColumnCustomWidth(jtAuditoria, 7, 100);
        jtAuditoria.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

    }

    private void setColumnCustomWidth(JTable table, int index, int width) {
        table.getColumnModel().getColumn(index).setMaxWidth(width);
        table.getColumnModel().getColumn(index).setMinWidth(width);
    }

    // POPULAR
    private void fillTableAuditoria() {
        DefaultTableModel tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };

        tableModel.addColumn("Id");
        tableModel.addColumn("Schema");
        tableModel.addColumn("Tabela");
        tableModel.addColumn("Usuário");
        tableModel.addColumn("Horário");
        tableModel.addColumn("Ação");
        tableModel.addColumn("Dados originais");
        tableModel.addColumn("Dados atuais");
        tableModel.addColumn("Query");

        audit.stream().filter(p -> applyTableFilters(p)).forEach(p -> {
            tableModel.addRow(
                    new Object[]{
                        p.getSequenceId(),
                        p.getSchemaName(),
                        p.getTableName(),
                        p.getUserName(),
                        p.getActionTimeStamp().getTime(),
                        p.getAction(),
                        p.getOriginalData(),
                        p.getNewData(),
                        p.getQuery()
                    }
            );
        });

        this.jtAuditoria.setModel(tableModel);
    }

    private boolean applyTableFilters(Auditoria audit) {
        if (cbAcao.getSelectedItem() != null) {
            return audit.getAction().toString() == cbAcao.getSelectedItem().toString();
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHeader = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbSubTitulo = new javax.swing.JLabel();
        jpBody = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtAuditoria = new javax.swing.JTable();
        cbAcao = new javax.swing.JComboBox<>();
        lbAcao = new javax.swing.JLabel();

        setBackground(new java.awt.Color(35, 40, 44));
        setPreferredSize(new java.awt.Dimension(575, 400));

        jpHeader.setBackground(new java.awt.Color(35, 40, 44));
        jpHeader.setPreferredSize(new java.awt.Dimension(333, 58));

        lbTitulo.setBackground(new java.awt.Color(204, 204, 204));
        lbTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(204, 204, 204));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("Auditoria");
        lbTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbTitulo.setPreferredSize(new java.awt.Dimension(321, 30));

        lbSubTitulo.setBackground(new java.awt.Color(204, 204, 204));
        lbSubTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbSubTitulo.setForeground(new java.awt.Color(204, 204, 204));
        lbSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSubTitulo.setText("Lista das alterações, inserções e exclusões");
        lbSubTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbSubTitulo.setPreferredSize(new java.awt.Dimension(300, 16));

        javax.swing.GroupLayout jpHeaderLayout = new javax.swing.GroupLayout(jpHeader);
        jpHeader.setLayout(jpHeaderLayout);
        jpHeaderLayout.setHorizontalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpHeaderLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpHeaderLayout.setVerticalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jpBody.setBackground(new java.awt.Color(35, 40, 44));

        jtAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtAuditoria.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtAuditoria);

        cbAcao.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cbAcao.setPreferredSize(new java.awt.Dimension(50, 21));
        cbAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAcaoActionPerformed(evt);
            }
        });

        lbAcao.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbAcao.setForeground(new java.awt.Color(204, 204, 204));
        lbAcao.setText("Ação:");

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbAcao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAcao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAcaoActionPerformed
        buildTableAuditoria();
    }//GEN-LAST:event_cbAcaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<CrudType> cbAcao;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpHeader;
    private javax.swing.JTable jtAuditoria;
    private javax.swing.JLabel lbAcao;
    private javax.swing.JLabel lbSubTitulo;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
