/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.kartodromo.view.form.home;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Arthur
 */
public class FormHome extends javax.swing.JPanel {

    public FormHome() {
        initComponents();

        buildPanelRankingGeral();
        buildPanelPrevisaoTempo();
        buildPanelCalendario();
        buildPanelRankingSemanal();
    }

    private void buildPanelRankingGeral() {
        lbRankingGeral.setText("Ranking Geral");
        lbIconRankingGeral.setIcon(new ImageIcon(getClass().getResource("/images/menuIcons/icon-trophy-light.png")));
    }

    private void buildPanelRankingSemanal() {
        lbRankingSemanal.setText("Ranking Semanal");
        lbIconRankingSemanal.setIcon(new ImageIcon(getClass().getResource("/images/menuIcons/icon-trophy-light.png")));
    }

    private void buildPanelPrevisaoTempo() {
        lbPrevisaoTempo.setText("Previsão do Tempo");
        lbIconPrevisaoTempo.setIcon(new ImageIcon(getClass().getResource("/images/menuIcons/icon-sun-cloud-light.png")));
    }

    private void buildPanelCalendario() {
        lbCalendario.setText("Calendário");
        lbIconCalendario.setIcon(new ImageIcon(getClass().getResource("/images/menuIcons/icon-calendar-light.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHeader = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbSubTitulo = new javax.swing.JLabel();
        jpBody = new javax.swing.JPanel();
        jpPrevisaoTempo = new javax.swing.JPanel();
        lbPrevisaoTempo = new javax.swing.JLabel();
        lbIconPrevisaoTempo = new javax.swing.JLabel();
        jpCalendario = new javax.swing.JPanel();
        jpHeaderCalendario = new javax.swing.JPanel();
        lbIconCalendario = new javax.swing.JLabel();
        lbCalendario = new javax.swing.JLabel();
        calendarCustom2 = new br.univates.kartodromo.view.form.home.calendario.CalendarCustom();
        jpRankingGeral = new javax.swing.JPanel();
        lbRankingGeral = new javax.swing.JLabel();
        lbIconRankingGeral = new javax.swing.JLabel();
        jpRankingGeral1 = new javax.swing.JPanel();
        lbIconRankingSemanal = new javax.swing.JLabel();
        lbRankingSemanal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(35, 40, 44));
        setPreferredSize(new java.awt.Dimension(575, 400));

        jpHeader.setBackground(new java.awt.Color(35, 40, 44));
        jpHeader.setPreferredSize(new java.awt.Dimension(333, 58));

        lbTitulo.setBackground(new java.awt.Color(204, 204, 204));
        lbTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(204, 204, 204));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("Página inicial");
        lbTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbTitulo.setPreferredSize(new java.awt.Dimension(321, 30));

        lbSubTitulo.setBackground(new java.awt.Color(204, 204, 204));
        lbSubTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbSubTitulo.setForeground(new java.awt.Color(204, 204, 204));
        lbSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSubTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbSubTitulo.setPreferredSize(new java.awt.Dimension(300, 16));

        javax.swing.GroupLayout jpHeaderLayout = new javax.swing.GroupLayout(jpHeader);
        jpHeader.setLayout(jpHeaderLayout);
        jpHeaderLayout.setHorizontalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpHeaderLayout.setVerticalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jpBody.setBackground(new java.awt.Color(35, 40, 44));

        jpPrevisaoTempo.setBackground(new java.awt.Color(21, 25, 28));
        jpPrevisaoTempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 211, 0)));
        jpPrevisaoTempo.setPreferredSize(new java.awt.Dimension(247, 150));

        lbPrevisaoTempo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbPrevisaoTempo.setForeground(new java.awt.Color(204, 204, 204));
        lbPrevisaoTempo.setText("P.T.");

        lbIconPrevisaoTempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconPrevisaoTempo.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jpPrevisaoTempoLayout = new javax.swing.GroupLayout(jpPrevisaoTempo);
        jpPrevisaoTempo.setLayout(jpPrevisaoTempoLayout);
        jpPrevisaoTempoLayout.setHorizontalGroup(
            jpPrevisaoTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrevisaoTempoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIconPrevisaoTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPrevisaoTempo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPrevisaoTempoLayout.setVerticalGroup(
            jpPrevisaoTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrevisaoTempoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrevisaoTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbIconPrevisaoTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPrevisaoTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jpCalendario.setBackground(new java.awt.Color(21, 25, 28));
        jpCalendario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 211, 0)));
        jpCalendario.setPreferredSize(new java.awt.Dimension(247, 150));

        jpHeaderCalendario.setBackground(new java.awt.Color(21, 25, 28));

        lbIconCalendario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconCalendario.setPreferredSize(new java.awt.Dimension(50, 50));

        lbCalendario.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbCalendario.setForeground(new java.awt.Color(204, 204, 204));
        lbCalendario.setText(".");

        javax.swing.GroupLayout jpHeaderCalendarioLayout = new javax.swing.GroupLayout(jpHeaderCalendario);
        jpHeaderCalendario.setLayout(jpHeaderCalendarioLayout);
        jpHeaderCalendarioLayout.setHorizontalGroup(
            jpHeaderCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIconCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbCalendario)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jpHeaderCalendarioLayout.setVerticalGroup(
            jpHeaderCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpHeaderCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIconCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpCalendarioLayout = new javax.swing.GroupLayout(jpCalendario);
        jpCalendario.setLayout(jpCalendarioLayout);
        jpCalendarioLayout.setHorizontalGroup(
            jpCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHeaderCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calendarCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpCalendarioLayout.setVerticalGroup(
            jpCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpHeaderCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendarCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpRankingGeral.setBackground(new java.awt.Color(21, 25, 28));
        jpRankingGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 211, 0)));
        jpRankingGeral.setPreferredSize(new java.awt.Dimension(100, 312));

        lbRankingGeral.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbRankingGeral.setForeground(new java.awt.Color(204, 204, 204));
        lbRankingGeral.setText(".");

        lbIconRankingGeral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconRankingGeral.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jpRankingGeralLayout = new javax.swing.GroupLayout(jpRankingGeral);
        jpRankingGeral.setLayout(jpRankingGeralLayout);
        jpRankingGeralLayout.setHorizontalGroup(
            jpRankingGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRankingGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIconRankingGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbRankingGeral)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpRankingGeralLayout.setVerticalGroup(
            jpRankingGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRankingGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRankingGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbRankingGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIconRankingGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpRankingGeral1.setBackground(new java.awt.Color(21, 25, 28));
        jpRankingGeral1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 211, 0)));
        jpRankingGeral1.setPreferredSize(new java.awt.Dimension(100, 312));

        lbIconRankingSemanal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconRankingSemanal.setPreferredSize(new java.awt.Dimension(50, 50));

        lbRankingSemanal.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbRankingSemanal.setForeground(new java.awt.Color(204, 204, 204));
        lbRankingSemanal.setText(".");

        javax.swing.GroupLayout jpRankingGeral1Layout = new javax.swing.GroupLayout(jpRankingGeral1);
        jpRankingGeral1.setLayout(jpRankingGeral1Layout);
        jpRankingGeral1Layout.setHorizontalGroup(
            jpRankingGeral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRankingGeral1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIconRankingSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbRankingSemanal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpRankingGeral1Layout.setVerticalGroup(
            jpRankingGeral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRankingGeral1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRankingGeral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbRankingSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIconRankingSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPrevisaoTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jpCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpRankingGeral1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpRankingGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpRankingGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addComponent(jpPrevisaoTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addComponent(jpRankingGeral1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 198, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.univates.kartodromo.view.form.home.calendario.CalendarCustom calendarCustom2;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpCalendario;
    private javax.swing.JPanel jpHeader;
    private javax.swing.JPanel jpHeaderCalendario;
    private javax.swing.JPanel jpPrevisaoTempo;
    private javax.swing.JPanel jpRankingGeral;
    private javax.swing.JPanel jpRankingGeral1;
    private javax.swing.JLabel lbCalendario;
    private javax.swing.JLabel lbIconCalendario;
    private javax.swing.JLabel lbIconPrevisaoTempo;
    private javax.swing.JLabel lbIconRankingGeral;
    private javax.swing.JLabel lbIconRankingSemanal;
    private javax.swing.JLabel lbPrevisaoTempo;
    private javax.swing.JLabel lbRankingGeral;
    private javax.swing.JLabel lbRankingSemanal;
    private javax.swing.JLabel lbSubTitulo;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
